
services:
  app:
    container_name: characters_app
    build:
      context: .
      dockerfile: ./CloudDbExample_CharactersCRUD/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=docker

  db:
    container_name: characters_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=characters_db
    ports:
      - "5432:5432"
